# .github/workflows/ci.yml

name: Build and Scan Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Lint with Ruff
      uses: chartboost/ruff-action@v1
      with:
        args: app

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t dev-env-api:latest .

    - name: Scan Docker image for security vulnerabilities
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: dev-env-api:latest

    - name: Mock push Docker image
      run: echo "Pretending to push dev-env-api:latest to registry (mock push)"

    - name: Done
      run: echo "✅ Lint, Build, Security Scan completed successfully!"
